version: '3'
services:
  web:
    restart: always
    image: node:12.19.0
    working_dir: /src
    ports:
    - "10001:10001"
    volumes:
    - ./:/src
    entrypoint: bash -c "npm install -production && node bit-animation.js"
